# Generated by Django 4.0.2 on 2022-02-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=30)),
                ('semail', models.EmailField(max_length=254)),
                ('sage', models.IntegerField()),
            ],
            options={
                'db_table': 'student1',
            },
        ),
    ]
