# Generated by Django 4.0.2 on 2022-02-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=30)),
                ('uage', models.IntegerField()),
                ('uemail', models.EmailField(max_length=254)),
                ('ucontact', models.IntegerField()),
            ],
            options={
                'db_table': 'user1',
            },
        ),
    ]
